name: GitHub Actions Main Branch
run-name: "${{github.actor}} performed ${{github.event_name}} on ${{github.head_ref || github.ref_name}}"

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Node.JS
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install Dependencies
              run: npm install

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Node.JS
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install Dependencies
              run: npm install
            
            - name: Run Tests
              run: npm run test
    
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Node.JS
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install Dependencies
              run: npm install
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-region: eu-central-1
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            
            - name: Synthesize CDK Stack
              run: |
                npx cdk synth > cdk_output.yaml
                echo "Synth output successful."
            
            - name: Deploy CDK Stack
              run: |
                npx cdk deploy
                echo "Deployed successfully."
